# Generated by Django 5.0.9 on 2025-01-26 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmName', models.CharField(blank=True, max_length=255)),
                ('farmLocation', models.CharField(blank=True, max_length=255)),
                ('farmSize', models.CharField(blank=True, max_length=50)),
                ('soilType', models.CharField(choices=[('Sandy', 'Sandy'), ('Clay', 'Clay'), ('Loamy', 'Loamy')], default='Sandy', max_length=20)),
                ('pHValue', models.FloatField(default=7.0)),
                ('currentCrop', models.CharField(choices=[('Maize', 'Maize'), ('Rice', 'Rice'), ('Beans', 'Beans')], default='Maize', max_length=20)),
                ('futureCrop', models.CharField(choices=[('Maize', 'Maize'), ('Rice', 'Rice'), ('Beans', 'Beans')], default='Beans', max_length=20)),
                ('irrigationSystem', models.CharField(choices=[('Manual', 'Manual'), ('Drip Irrigation', 'Drip Irrigation'), ('Sprinkler System', 'Sprinkler System'), ('Rain-fed', 'Rain-fed')], default='Manual', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
